name: Ironman challenge lighthouse-ci demo
on:
  push:
    branches: [main, master]
    paths:
      - "app/**"
      - "public/**"
      - "next.config.ts"
      - "package.json"
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, build
        run: |
          yarn
          npm run build
      - name: run lighthouse-ci
        run: |
          npm install -g @lhci/cli@0.3.x
          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
        env:
          LHCI_GITHUB_APP_TOKEN: 7ww80dXxtiFHfkMQ:72324073:3iNDbBHU
