name: Lighthouse CI

on:
  push:
    branches:
      - main # 或你希望觸發的分支

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 安裝 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: 安裝依賴
        run: npm install

      - name: 執行 Lighthouse CI
        run: npx lhci autorun
